/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.Cadastro.TelaCadastroEdificio;
import view.Cadastro.TelaCadastroAreaCompartilhada;
import view.Cadastro.TelaCadastroAreaCompartilhadaEdificio;
import view.Cadastro.TelaCadastroCustoNivel1;
import view.Cadastro.TelaCadastroCustoNivel2;
import view.Cadastro.TelaCadastroFornecedor;
import view.Cadastro.TelaCadastroProprietario;
import view.Cadastro.TelaCadastroSindicoProfissional;
import view.Cadastro.TelaCadastroUnidade;
import view.Cadastro.TelaCadastroUnidadeCondomino;
import controller.ControllerCadastroEdificio;
import controller.ControllerCadastroAreaCompartilhada;
import controller.ControllerCadastroAreaCompartilhadaEdificio;
import controller.ControllerCadastroCustoNivel1;
import controller.ControllerCadastroCustoNivel2;
import controller.ControllerCadastroFornecedor;
import controller.ControllerCadastroProprietario;
import controller.ControllerCadastroSindicoProfissional;
import controller.ControllerCadastroUnidade;
import controller.ControllerCadastroUnidadeCondominio;

/**
 *
 * @author aluno
 */
public class TelaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaMenuPrincipal() {
        initComponents();

        jMenuItem3.addActionListener(evt -> abrirCadastroUnidade());
        jMenuItem12.addActionListener(evt -> abrirCadastroUnidadeCondominio());
        jMenuItem9.addActionListener(evt -> abrirCadastroAreaCompartilhadaEdificio());
        jMenuItem4.addActionListener(evt -> abrirCadastroProprietario());
        jMenuItem5.addActionListener(evt -> abrirCadastroFornecedor());
        jMenuItem6.addActionListener(evt -> abrirCadastroSindicoProfissional());
        jMenuItem10.addActionListener(evt -> abrirCadastroCustoNivel1());
        jMenuItem7.addActionListener(evt -> System.exit(0));
    }

    private void abrirCadastroUnidade() {
        TelaCadastroUnidade tela = new TelaCadastroUnidade(null, true);
        new ControllerCadastroUnidade(tela);
        tela.setVisible(true);
    }

    private void abrirCadastroUnidadeCondominio() {
        TelaCadastroUnidadeCondomino tela = new TelaCadastroUnidadeCondomino(null, true);
        new ControllerCadastroUnidadeCondominio(tela);
        tela.setVisible(true);
    }

    private void abrirCadastroAreaCompartilhadaEdificio() {
        TelaCadastroAreaCompartilhadaEdificio tela = new TelaCadastroAreaCompartilhadaEdificio(null, true);
        new ControllerCadastroAreaCompartilhadaEdificio(tela);
        tela.setVisible(true);
    }

    private void abrirCadastroProprietario() {
        TelaCadastroProprietario tela = new TelaCadastroProprietario(null, true);
        new ControllerCadastroProprietario(tela);
        tela.setVisible(true);
    }

    private void abrirCadastroFornecedor() {
        TelaCadastroFornecedor tela = new TelaCadastroFornecedor(null, true);
        new ControllerCadastroFornecedor(tela);
        tela.setVisible(true);
    }

    private void abrirCadastroSindicoProfissional() {
        TelaCadastroSindicoProfissional tela = new TelaCadastroSindicoProfissional(null, true);
        new ControllerCadastroSindicoProfissional(tela);
        tela.setVisible(true);
    }

    private void abrirCadastroCustoNivel1() {
        TelaCadastroCustoNivel1 tela = new TelaCadastroCustoNivel1(null, true);
        new ControllerCadastroCustoNivel1(tela);
        tela.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jMenu2.setText("Cadastros");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Company.png"))); // NOI18N
        jMenuItem2.setText("Edificio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Home.png"))); // NOI18N
        jMenuItem3.setText("Unidade ");
        jMenu2.add(jMenuItem3);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Black bookmark.png"))); // NOI18N
        jMenuItem12.setText("Unidade Condomínio");
        jMenu2.add(jMenuItem12);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Flag.png"))); // NOI18N
        jMenuItem8.setText("Área Compartilhada");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Blue pin.png"))); // NOI18N
        jMenuItem9.setText("Área Compartilhada Edifício");
        jMenu2.add(jMenuItem9);
        jMenu2.add(jSeparator1);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Boss.png"))); // NOI18N
        jMenuItem4.setText("Proprietário");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Buy.png"))); // NOI18N
        jMenuItem5.setText("Fornecedor");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Briefcase.png"))); // NOI18N
        jMenuItem6.setText("Síndico Profissional");
        jMenu2.add(jMenuItem6);
        jMenu2.add(jSeparator2);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Dollar.png"))); // NOI18N
        jMenuItem10.setText("Custo Nível 1");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Dollar.png"))); // NOI18N
        jMenuItem11.setText("Custo Nível 2");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);
        jMenu2.add(jSeparator3);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancel.png"))); // NOI18N
        jMenuItem7.setText("Sair");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Movimentos");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");
        jMenu4.setActionCommand("Relatórios cagada");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ajuda");

        jMenuItem1.setText("Sobre");
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        TelaCadastroEdificio telaCadastroEdificio = new TelaCadastroEdificio(null, true);
        ControllerCadastroEdificio controllerCadastroEdificio = new ControllerCadastroEdificio(telaCadastroEdificio);
        telaCadastroEdificio.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        TelaCadastroAreaCompartilhada tela = new TelaCadastroAreaCompartilhada(null, true);
        new ControllerCadastroAreaCompartilhada(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        TelaCadastroCustoNivel2 tela = new TelaCadastroCustoNivel2(null, true);
        new ControllerCadastroCustoNivel2(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
